name = "todo-to-learn-to-play"
compatibility_date = "2026-07-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "todo-to-learn-to-play-db"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"
